package com.saragarcia6123.weatherapp.domain

enum class WeatherCondition {
    CLEAR,
    SUNNY,
    PARTLY_CLOUDY,
    MOSTLY_CLOUDY,
    CLOUDY,
    OVERCAST,
    FOGGY,
    HAZY,
    MISTY,
    RAINY,
    SHOWERS,
    DRIZZLE,
    LIGHT_RAIN,
    MODERATE_RAIN,
    HEAVY_RAIN,
    THUNDERSTORMS,
    LIGHTNING,
    SNOWY,
    FLURRIES,
    LIGHT_SNOW,
    MODERATE_SNOW,
    HEAVY_SNOW,
    BLIZZARD,
    SLEET,
    FREEZING_RAIN,
    DUSTY,
    WINDY,
    BREEZY,
    TORNADO,
    HURRICANE,
    CYCLONE,
    TROPICAL_STORM,
    SANDSTORM,
    SMOKE,
    ASHFALL,
    VOLCANIC_ASH
}

